version: 0.1

phases:
  build:
    commands:
      - ./gradlew bootjar
      - ls
      - cd build
      - ls
      - cd libs
      - ls
 
artifacts:
  files:
    - ./build/libs/pokemon-0.0.1-SNAPSHOT.jar
